### ISSUE TITLE
User Register API (Email)

### ISSUE THREAD

**Issue by KiWooyoung** [Mash-Up-MapC/MapC-backend#10]
# `<Issue Title>`

## Request

| HTTP Method | URI |
|:------------|:----|
| | |

- Header

| Name | Value | Description |
|:-----|:-----|:------------|
| | | |

- parameter

| Name | Type | Description |
|:-----|:-----|:------------|
| | | |

- example
```
FIXME: fill response data
```

---

<br>

### Success
- Status: 
- Header

| Name | Value | Description |
|:-----|:-----|:------------|
| | | |

```
FIXME: fill response data
```

<br>

### Fail

| Status | Description |
|:-------|:------------|
| | |

#### `<Status>`
```
FIXME: fill response data
```

---

<br>

---

<br>

## relate to issue
> FIXME: Describe relate to issue
* `<issue title> <#issue number>`

<br>

> #### Reference
> FIXME: fill reference link
> * `[title](link)`

<br>

## Check List
- [ ] issue 제목은 유의미한가?
- [ ] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [ ] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [ ] 유의미한 Label을 추가했는가?
- [ ] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [ ] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?

**Comment by opklnm102** [comment]
pivot으로 인해 해당 기능은 보류하고 issue는 close할께요. 
추후 필요하면 reopen해서 사용하도록해요
