### ISSUE TITLE
DB Table 모델링

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#11]
# DB Table을 모델링
* DB Table을 모델링한다

## 초안
![mapc_db_erd_v1](https://user-images.githubusercontent.com/8637090/42408460-ee7167ec-8207-11e8-82de-7e186da0bc7a.png)

<br>

### 완료 조건
- [x] comment로 ERD 초안이 공유된다
- [x] 공유된 초안으로 리뷰를 진행한다

<br> 

## relate to issue
* Entity Modeling하기(#33)

<br>

> #### Reference
> * [디자인 - zeplin](https://app.zeplin.io/project/5b6bab573b0600688b8ec7d4/dashboard)

**Comment by opklnm102** [comment]
@KiWooyoung 

#### logAlarm
* 해당 테이블은 무슨 용도에요?

#### use
* selection_color은 유저가 선택한 색인거죠?

#### fashioPost
* count는 like 횟수인거죠?

#### question
* content에는 어떤게 들어가요?

#### weather
* 날씨는 지역만 관련이 있나요..?
  * 날씨는 지역과 일시에 관련이 있을거 같은데, 일시에 대한 정보가 빠진듯..?

#### recommendation
* 특정 날씨에 추천할 옷 리스트들을 관리할 테이블인거죠?

#### clothes
* recommendation에 들어갈 옷들을 관리할 테이블인가요..?
* 만약 맞다면 그렇다면 recommendation_id를 clothes가 가지고 있으면 문제될 여지는 없나요?

#### etc
* 현재 버전은 이메일 로그인만 고려된 버전인거죠...? oauth는 고려 노노?

**Comment by KiWooyoung** [comment]
logAlarm - 제플린에 알람이 있길래 일단 추가해봤습니다.

user - 그렇습니다.

fashioPost - 네.

question - 설명이 있을줄 알았는데, 제플린에 QnP 주제 이외에 설명이 없네요. - 없다면 빼야할듯

weather - 음 좀 더 생각해볼게요.

recommendation - 넹

clothes - 아, 관계가 반대로 설정된거 같은데 음.. 그러면 weather 테이블이랑 recommendation 관계도 다시 설정해야겠네요. 수정해야할 부분인거 같아요.

etc - 이메일 방식 이외의 방법은 수요일날 이야기 확실히 해쓰면 해요.

**Comment by opklnm102** [comment]
<img width="911" alt="mapc_erd_v2" src="https://user-images.githubusercontent.com/8637090/44301804-3a939480-a358-11e8-88b6-3f1f40ba85f1.png">

* 예약 기능은 현재 어떤식으로 구현될지 몰라서 두군데 버스 회사 웹사이트를 참고하여 스키마를 만들었습니다
* 현재 위치(위,경도)를 바탕으로 주변 정보를 가이드 추천 해주는 기능을 위해 일단 station 테이블에 위경도 컬럼을 추가 헀습니다
  * 이 기능은 mongodb geospatial이 괜찮다 하는데 몽고디비 연동해보는것도 좋을거 같습니다
* 서울 시티투어 버스에서 좌석 보장도 안될 수도 있고 예약 차종도 변경될 수 있고 버스회사 사정에 따라서 유동적으로 운영 중인 거 같아 뭔가 딱딱 떨어지게 만드는 게 어렵다고 생각이 들었습니다
> by @KiWooyoung

**Comment by opklnm102** [comment]
올리고 보니까 단순 예약이라서 booking_item 테이블은 불필요 해보이기도 하네요...
> by @KiWooyoung

**Comment by opklnm102** [comment]
디자인 보니깐 코스 테이블에 주요 관광지, 루트를 지도에 그릴 수 있는 정도의 경로 데이터, 코스별 부가 정보를 위한 컬럼이 필요할듯해요

**Comment by KiWooyoung** [comment]
넵 확인했습니당.
https://app.zeplin.io/project/5b6bab573b0600688b8ec7d4/screen/5b6c401058744c75b878aa91
요 페이지 말씀하시는거죠~?

**Comment by KiWooyoung** [comment]
경로 데이터는 (위,경도) 를 말씀하시는거로 생각한다면, station 클래스에 위경도를 추가했는데 다른 말씀이신가여? / 코스별 부가 정보를 위한 컬럼및테이블은 추가할게요!

**Comment by opklnm102** [comment]
station 테이블에 있는 위경도만으로 코스별 상세정보의 지도에 있는 루트를 그릴 수 있는지 우선 확인해봐야할듯해요
[코스별 상세정보 화면의 지도에 그려질 루트 정보 질문 - MapC android](https://github.com/Mash-Up-MapC/MapC-android/issues/23) 여기에 답글 달리는거 보고 테이블 수정하면 될거 같아요

**Comment by KiWooyoung** [comment]
확인했습니다.

**Comment by opklnm102** [comment]
@KiWooyoung 우리 근데 다국어도 고려해야하는데.... 이건 다른 이슈에서 진행하고 해당 이슈는 지금까지 완성된 ERD 공유 여기에 공유해주시고 close하면 될듯해요

**Comment by KiWooyoung** [comment]
우선 추가된 디자인&기획 에 따라서 스키마를 변경 하였습니다.

![image](https://user-images.githubusercontent.com/16856660/44593946-c5b0d680-a7ff-11e8-869e-67d858f39ca8.png)

**Comment by opklnm102** [comment]
API 구현 후에 다국어 지원(#42)에 대해서도 고려해보죠

**Comment by KiWooyoung** [comment]
알겠습니당
