### ISSUE TITLE
user story로 issue 생성하기

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#12]
# user story로 issue 생성하기
* story의 우선 순위를 나누고, story끼리 모아서 milestone으로 만든다
* 해당 story를 완성시킬 수 있도록 작업들을 나누어 story 하위에 issue를 생성한다
  * 현재 생성된 issue들도 story 하위로 이동 시킨다
* 완성된 milestone별로 deploy할 수 있도록 milestone branch를 만들어서 관리한다 

<br>

## [Setting up your first ZenHub Epic](https://help.zenhub.com/support/solutions/articles/43000010341-setting-up-your-first-zenhub-epic)의 내용 중
| Agile | GitHub |
|:--:|:--:|
| Epic | Epic |
| User Story | GitHub issue |
| Sub-Task | Markdown Checklist |
* 이렇게 나와있지만 Sub-Task를 Mackdown Checklist로만 관리하면 세부 내용을 놓칠 수 있을 것 같아서

| Agile | GitHub |
|:--:|:--:|
| Epic | Milestone |
| User Story | Epic of ZenHub |
| Sub-Task | GitHub issue |
* 우리는 위와 같이 생각하고 작업한다

<br>

### 완료 조건
- [x] 1개의 milestone 생성
- [x] mileston 하위의 story 생성
- [x] story 하위의 sub task 생성
- [ ] mileston별 branch 존재

<br>

> #### 참고
> * [Setting up your first ZenHub Epic](https://help.zenhub.com/support/solutions/articles/43000010341-setting-up-your-first-zenhub-epic)

<br> 

## relate to issue
* issue tracking을 통해 프로젝트를 진행하기 #15

**Comment by KiWooyoung** [comment]
오 이건 뭔가요..

**Comment by opklnm102** [comment]
milestone별로 관리하기에는 번거로울거 같아서 그냥 develop에서 진행하기로...
