### ISSUE TITLE
ZenHub plugin 설치

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#14]
# ZenHub plugin 설치 
* co-worker들은 ZenHub plugin을 이용해 같은 interface를 사용한다
* [ZenHub for GitHub - Chrome web store](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd)에서 설치 후 완료되면 comment 달아주세요

<br>

> #### 참고
> * [Setting up your first ZenHub Board](https://www.zenhub.com/guides/setup-my-zenhub-boards)
> * [Setting up your first ZenHub Epic](https://help.zenhub.com/support/solutions/articles/43000010341-setting-up-your-first-zenhub-epic)

<br> 

## relate to issue
* issue tracking을 통해 프로젝트를 진행하기 #15

**Comment by KiWooyoung** [comment]
설치완료 햿습니당

**Comment by korea8378** [comment]
설치완료 했습니다.
