### ISSUE TITLE
Github를 위한 Slack webhook 설정

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#16]
# Github를 위한 Slack webhook 설정
* contributor들이 작업 상황을 slack을 통해 실시간으로 파악할 수 있도록 아래 event에 대해 Slack webhook을 설정한다
  * 주요 branch(master, release, develop)에 대한 PR 생성
    *  주요 branch로 direct merge는 불가능하기 때문에 push가 아닌 PR에 대해서만 설정
  * issue 생성

## 완료 조건
- [x] issue 생성시 slack channel로 noti가 온다
- [x] PR 생성시 slack channel로 noti가 온다

<br> 

## relate to issue
* issue tracking을 통해 프로젝트를 진행하기 #15

**Comment by opklnm102** [comment]
완료조건 충족했으므로 close 할께요

**Comment by KiWooyoung** [comment]
슬랙 채널 어디에 훅 걸었나요~?!

**Comment by KiWooyoung** [comment]
아 찾았어요 헷
