### ISSUE TITLE
개발 규칙 정하기

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#17]
# 개발 규칙 정하기
* 협업을 하기 위해 변수 네이밍 등 코딩 컨벤션과 git branch 전략을 위한 branch naming 등을 정해 문서화 한다

<br>

### 완료 조건
- [x] 정한 내용을 어딘가에 기록해 코멘트를 남긴다
   * github wiki, google docs, evernote 등

<br>

> #### 참고
> * [9tique-android wiki](https://github.com/mash-up-kr/9tique-android/wiki/2.-Git)

<br> 

## relate to issue
* issue tracking을 통해 프로젝트를 진행하기 #15

**Comment by opklnm102** [comment]
### branch 전략
* git flow를 따른다

### branch naming
* `issue number-issue name`
* ex) 16-defining-development-rules

### commit message
* `[#issue number>] [behavior(upper case)] message`
* ex. `[#16] [FIX] 개발 규칙 오타 수정`

### 개발 프로세스
1. issue 생성
2. issue 기반 branch 생성
3. issue와 관련된 feature 개발 완료
   * 개인별 repo or branch에서는 commit 각자 스타일에 맞춰
4. merge commit 생성시(PR) commit message rule에 맞춰서 sqash merge를 위해 commit history 단장
5. PR이 주요 branch로 merge되기 위한 조건
   * 최소 1명의 review의 approve
   * CI로 인한 build success
   * test case 작성 - optional 
6. merge 후 feature branch 제거
7. issue close

<br>

@KiWooyoung , @korea8378 확인하고 부족 or 이상한 것, 좋다 등등 자유롭게 의견주세요. 2일간 comment 없으면 wiki에 정리하고 해당 issue close할께요

**Comment by korea8378** [comment]
규칙에 맞게 열심히 해보겠습니다~~~!

**Comment by opklnm102** [comment]
[Mash-Up-MapC wiki - 개발 규칙](https://github.com/Mash-Up-MapC/MapC-backend/wiki/%EA%B0%9C%EB%B0%9C-%EA%B7%9C%EC%B9%99)에 정리 완료
