### ISSUE TITLE
AWS 계정 & 인프라 셋팅하기

### ISSUE THREAD

**Issue by KiWooyoung** [Mash-Up-MapC/MapC-backend#37]
# AWS 계정 & 인프라 셋팅하기
* 서버팀 AWS 접근 사용자 추가 - IAM
* 기본 인프라 EC2, RDS, S3 생성
* Ubuntu Password User 생성

### 완료 조건
- [x] 서버팀 AWS 접근 사용자 추가 - IAM
- [x] 기본 인프라 EC2, RDS, S3 생성
- [x] Ubuntu Password User 생성

<br>

## relate to issue
*  Backend architecture 구성하기(#39)

<br> 

> #### Reference
> * [아마존 웹 서비스를 다루는 기술](http://pyrasis.com/aws.html)

## Check List
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [ ] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 Label을 추가했는가?
- [x] Assginees를 추가했는가?
- [x] Estimate를 추가했는가?
- [x] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?

**Comment by opklnm102** [comment]
AWS IAM 등이 생성되어 카톡으로 공유받았으므로 close할께요
추후 네트워크 구성도 추가하면 좋을듯
