### ISSUE TITLE
Color 배색 추천 API

### ISSUE THREAD

**Issue by korea8378** [Mash-Up-MapC/MapC-backend#5]
# Color 배색 추천 API
* Color 배색 추천 API를 구현한다
## Request
* endpoint :  GET /color/coloration?selectionColor="color HEX"
* Content-Type : application/json

### Success
* Content-Type : application/json
<pre><code>
[
    {
        "color" : "#000000"
    },
    {
        "color" : "#000000"
    },
    {
        "color" : "#000000"
    },
    {
        "color" : "#000000"
    },
    {
        "color" : "#000000"
    }
]
</pre></code>
### Fail
* 500 : INTERNAL SERVER ERROR

**Comment by opklnm102** [comment]
pivot으로 인해 해당 기능이 사라져 close할께요
